apiVersion: apps/v1
kind: Deployment
metadata:
  name: vul-flask
spec:
  selector:
    matchLabels:
      app: vul-flask
  replicas: 1
  template:
    metadata:
      labels:
        app: vul-flask
    spec:
      containers:
      - image: <image-name>
        imagePullPolicy: Always
        name: vul-flask
        ports:
        - containerPort: 5050
        securityContext:
          # the privileged flag will be marked as a critical risk
          privileged: true
          readOnlyRootFilesystem: true
